;;; Headless Common Lisp implementation of the shared game contract.
(defstruct game state mask x z elapsed score hazard-x hazard-direction)
(defun new-game () (make-game :state 0 :mask 0 :x 0.0 :z 0.0 :elapsed 0.0 :score 0.0 :hazard-x 0.0 :hazard-direction 1.0))
(defun d2 (ax az bx bz) (+ (expt (- ax bx) 2) (expt (- az bz) 2)))
(defun clamp (v low high) (max low (min high v)))
(defun update (g seconds &optional (mx 0.0) (mz 0.0) (boost nil) (restart nil))
  (if restart (return-from update (new-game)))
  (when (or (= (game-state g) 2) (= (game-state g) 3)) (return-from update g))
  (when (= (game-state g) 0) (setf (game-state g) 1))
  (let* ((dt (clamp seconds 0.0 0.25)) (speed (if boost 7.0 4.0)))
    (setf (game-x g) (clamp (+ (game-x g) (* (clamp mx -1.0 1.0) speed dt)) -10.0 10.0)
          (game-z g) (clamp (+ (game-z g) (* (clamp mz -1.0 1.0) speed dt)) -10.0 10.0)
          (game-elapsed g) (+ (game-elapsed g) dt)
          (game-hazard-x g) (+ (game-hazard-x g) (* (game-hazard-direction g) 2.0 dt)))
    (when (>= (game-hazard-x g) 7.0) (setf (game-hazard-x g) 7.0 (game-hazard-direction g) -1.0))
    (when (<= (game-hazard-x g) -7.0) (setf (game-hazard-x g) -7.0 (game-hazard-direction g) 1.0))
    (loop for cell in '((-6.0 0.0) (0.0 -5.0) (6.0 0.0)) for i from 0
          for cx = (first cell) for cz = (second cell) do
      (let ((bit (ash 1 i))) (when (and (zerop (logand (game-mask g) bit)) (<= (d2 (game-x g) (game-z g) cx cz) .81))
        (setf (game-mask g) (logior (game-mask g) bit)) (incf (game-score g) 100.0))))
    (if (or (<= (d2 (game-x g) (game-z g) (game-hazard-x g) 3.0) 3.0625) (>= (game-elapsed g) 60.0))
        (setf (game-state g) 3)
        (when (and (= (game-mask g) 7) (<= (d2 (game-x g) (game-z g) 0.0 -9.0) 1.96))
          (setf (game-state g) 2) (incf (game-score g) 1000.0)))) g)
(defun step-game (g x z &optional (boost t)) (update g .25 x z boost))
(defun collect (g) (dotimes (i 4) (step-game g -1 0)) (dotimes (i 4) (step-game g 1 0)) (dotimes (i 3) (step-game g 0 -1)) (dotimes (i 4) (step-game g 1 0)))
(defun run-scenario (name)
  (let ((g (new-game)))
    (cond ((or (string= name "collection") (string= name "win")) (collect g) (when (string= name "win") (dotimes (i 3) (step-game g -1 0)) (dotimes (i 2) (step-game g 0 -1))))
          ((string= name "hazard") (dotimes (i 3) (step-game g 0 1 nil)))
          ((string= name "loss") (dotimes (i 241) (step-game g 0 0 nil)))
          ((string= name "restart") (step-game g 1 0) (setf g (update g 0 0 0 nil t)))) g))
(let* ((name (or (second sb-ext:*posix-argv*) "startup")) (g (run-scenario name)))
  (format t "~d ~d ~,4f ~,4f ~,4f ~,4f~%" (game-state g) (game-mask g) (game-x g) (game-z g) (game-elapsed g) (game-score g)))